---
- hosts: all
  tasks:
  - name: install java
    yum:
      name: java-1.8.0-openjdk.i686
      state: present
    
  - name: install tomcat7
    yum:
      name: tomcat
      state: present
   
  - name: install jenkins
    get_url:
      url: http://ftp-chi.osuosl.org/pub/jenkins/war/2.133/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war

  - name: enable and start service
    service:
      name: tomcat
      state: started
      enabled: yes
